document.write("<!--头部开始-->");
document.write("<div class=\"col-lg-12 col-xs-12 head_main\">");
document.write("    <span class=\"visible-sm-block visible-md-block visible-xs-block\" onclick=\"showleftmenu();\">");
document.write("        <img src=\".\/image\/list.png\" alt=\"\">");
document.write("    <\/span>");
document.write("    ");
document.write("    <div class=\"head_logo col-xs-12 col-lg-4\">");
document.write("        <a href=\".\/index.html\">Fox-Fish's blog<\/a>");
document.write("    <\/div>");
document.write("    <div class=\"head_item col-lg-8 visible-lg-block\">");
document.write("        <li>");
document.write("            <a href=\".\/container.html\">About<\/a>");
document.write("        <\/li>");
document.write("        <li>");
document.write("            <a href=\".\/datapage.php?md=%27.\/article\/acmSkills.json%27\">ACM技能树<\/a>");
document.write("        <\/li>");
document.write("        <li>");
document.write("            <a href=\".\/gamecs.html\">STG测试间<\/a>");
document.write("        <\/li>");
document.write("        <li>");
document.write("            <a href=\"#\">特效实验室<\/a>");
document.write("        <\/li>");
document.write("    <\/div>");
document.write("<\/div>");
document.write("<!--头部结束-->");
document.write("<!--头图开始-->");
document.write("<div class=\"container\">");
document.write("    <div id=\"headimg\" class=\"col-xs-12 col-lg-12 headimg_main\">");
document.write("        <img id=\"imgs\" src=\"\" onclick=\"cimages()\">");
document.write("    <\/div>");
document.write("<\/div>");
document.write("<!--头图结束-->");
