document.write("<div id=\"leftmenu_right\" onclick=\"showleftmenu();\"><\/div>");
document.write("<div id=\"leftmenu\" class=\"all_leftmenu\">");
document.write("    <div class=\"all_leftlogo\">");
document.write("        <img src=\".\/image\/intro.jpg\">");
document.write("        <a href=\"#\">");
document.write("            <h1>Fox-Fish's blog<\/h1>");
document.write("        <\/a>");
document.write("        <p>编程与东方project的结合<\/p>");
document.write("        <p>╭( ･ㅂ･)و ̑̑<\/p>");
document.write("    <\/div>");
document.write("    <div class=\"all_leftdata\">");
document.write("        <li>");
document.write("            <a href=\".\/container.html\">About<\/a>");
document.write("        <\/li>");
document.write("        <li>");
document.write("            <a href=\".\/datapage.php?md=%27.\/article\/acmSkills.json%27\">ACM技能树<\/a>");
document.write("        <\/li>");
document.write("        <li>");
document.write("            <a href=\".\/gamecs.html\">STG测试间<\/a>");
document.write("        <\/li>");
document.write("        <li>");
document.write("            <a href=\"#\">特效实验室<\/a>");
document.write("        <\/li>");
document.write("        <li>");
document.write("            <a href=\"#\">特效实验室<\/a>");
document.write("        <\/li>");
document.write("        <li>");
document.write("            <a href=\"#\">特效实验室<\/a>");
document.write("        <\/li>");
document.write("        <li>");
document.write("            <a href=\"#\">特效实验室<\/a>");
document.write("        <\/li>");
document.write("        <li>");
document.write("            <a href=\"#\">特效实验室<\/a>");
document.write("        <\/li>");
document.write("    <\/div>");
document.write("<\/div>");
